apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eco-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RomanMartynyshyn/eco-infra.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
